In [3]:
import pandas as pd
import numpy as np

In [280]:
file = pd.read_excel("suicide-blasts-final.xlsx")
file.head()

,S#,Date,Year,Islamic Date,Blast Day Type,Holiday Type,Time,City,Latitude,Longitude,...,Targeted Sect if any,Killed Min,Killed,Injured Min,Injured,No. of Suicide Blasts,Explosive Weight (max),Hospital Names,Temperature(C),Temperature(F)
0,1,Sunday-November 19-1995,1995,25 Jumaada al-THaany 1416 A.H,Holiday,Weekend,NaN,Islamabad,33.7180,73.0718,...,NaN,14.0,15.0,NaN,60,2.0,NaN,NaN,15.835,60.503
1,2,Monday-November 6-2000,2000,10 SHa`baan 1421 A.H,Working Day,NaN,NaN,Karachi,24.9918,66.9911,...,NaN,NaN,3.0,NaN,3,1.0,NaN,NaN,23.770,74.786
2,3,Wednesday-May 8-2002,2002,25 safar 1423 A.H,Working Day,NaN,07:45:00,Karachi,24.9918,66.9911,...,Christian,13.0,15.0,20.0,40,1.0,2.5 Kg,1.Jinnah Postgraduate Medical Center 2. Civil ...,31.460,88.628
3,4,Friday-June 14-2002,2002,3 Raby` al-THaany 1423 A.H,Working Day,NaN,11:10:00,Karachi,24.9918,66.9911,...,Christian,NaN,12.0,NaN,51,1.0,NaN,NaN,31.430,88.574
4,5,Friday-July 4-2003,2003,4 Jumaada al-awal 1424 A.H,Working Day,NaN,NaN,Quetta,30.2095,67.0182,...,Shiite,44.0,47.0,NaN,65,1.0,NaN,1.CMH Quetta\n2.Civil Hospital 3. Boland Medic...,33.120,91.616

In [281]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 496 entries, 0 to 495
Data columns (total 27 columns):
S#                         496 non-null int64
Date                       496 non-null object
Year                       496 non-null int64
Islamic Date               342 non-null object
Blast Day Type             486 non-null object
Holiday Type               72 non-null object
Time                       285 non-null object
City                       496 non-null object
Latitude                   493 non-null float64
Longitude                  493 non-null object
Province                   496 non-null object
Location                   493 non-null object
Location Category          460 non-null object
Location Sensitivity       460 non-null object
Open/Closed Space          461 non-null object
Influencing Event/Event    191 non-null object
Target Type                470 non-null object
Targeted Sect if any       97 non-null object
Killed Min                 350 non-null float64
Killed                     480 non-null float64
Injured Min                365 non-null float64
Injured                    464 non-null object
No. of Suicide Blasts      414 non-null float64
Explosive Weight (max)     172 non-null object
Hospital Names             297 non-null object
Temperature(C)             491 non-null float64
Temperature(F)             489 non-null float64
dtypes: float64(7), int64(2), object(18)
memory usage: 104.7+ KB

In [282]:
file

,S#,Date,Year,Islamic Date,Blast Day Type,Holiday Type,Time,City,Latitude,Longitude,...,Targeted Sect if any,Killed Min,Killed,Injured Min,Injured,No. of Suicide Blasts,Explosive Weight (max),Hospital Names,Temperature(C),Temperature(F)
0,1,Sunday-November 19-1995,1995,25 Jumaada al-THaany 1416 A.H,Holiday,Weekend,NaN,Islamabad,33.718000,73.0718,...,NaN,14.0,15.0,NaN,60,2.0,NaN,NaN,15.835,60.503
1,2,Monday-November 6-2000,2000,10 SHa`baan 1421 A.H,Working Day,NaN,NaN,Karachi,24.991800,66.9911,...,NaN,NaN,3.0,NaN,3,1.0,NaN,NaN,23.770,74.786
2,3,Wednesday-May 8-2002,2002,25 safar 1423 A.H,Working Day,NaN,07:45:00,Karachi,24.991800,66.9911,...,Christian,13.0,15.0,20.0,40,1.0,2.5 Kg,1.Jinnah Postgraduate Medical Center 2. Civil ...,31.460,88.628
3,4,Friday-June 14-2002,2002,3 Raby` al-THaany 1423 A.H,Working Day,NaN,11:10:00,Karachi,24.991800,66.9911,...,Christian,NaN,12.0,NaN,51,1.0,NaN,NaN,31.430,88.574
4,5,Friday-July 4-2003,2003,4 Jumaada al-awal 1424 A.H,Working Day,NaN,NaN,Quetta,30.209500,67.0182,...,Shiite,44.0,47.0,NaN,65,1.0,NaN,1.CMH Quetta\n2.Civil Hospital 3. Boland Medic...,33.120,91.616
5,6,Thursday-December 25-2003,2003,2 Thw al-Qi`dah 1424 A.H.,Holiday,Christmas/birthday of Quaid-e-Azam,1:40:00 PM/1:42:00 PM,Rawalpindi,33.605800,73.0437,...,NaN,16.0,18.0,NaN,50,2.0,30kg in each car,1.District headquarters \nHospital,9.445,49.001
6,7,Saturday-February 28-2004,2004,8 MuHarram 1425 A.H,Working Day,NaN,NaN,Rawalpindi,33.605800,73.0437,...,shiite,NaN,1.0,3.0,4,1.0,NaN,NaN,15.275,59.495
7,8,Friday-May 7-2004,2004,18 Raby` al-awal 1425 A.H,Working Day,NaN,1:20:00/1:17:00 PM,Karachi,24.991800,66.9911,...,shiite,14.0,15.0,96.0,200,1.0,2kg,Civil hospital,33.860,92.948
8,9,Monday-May 31-2004,2004,NaN,Working Day,NaN,evening,Karachi,24.991800,66.9911,...,Shiite,16.0,18.0,NaN,35,1.0,NaN,Civil hospital-Liaquat National hospital-Jinna...,31.605,88.889
9,10,Thursday-June 3-2004,2004,15 Raby` al-THaany 1425 A.H,Working Day,NaN,NaN,North waziristan,32.974600,70.1456,...,NaN,NaN,2.0,NaN,2,1.0,NaN,NaN,27.180,80.924
10,11,Wednesday-July 28-2004,2004,11 Jumaada al-THaany 1425 A.H,Working Day,NaN,8:50:PM,Kohat,33.583300,71.4333,...,NaN,2.0,3.0,NaN,3,2.0,NaN,CMH Kohat,32.430,90.374
11,12,Friday-July 30-2004,2004,13 Jumaada al-THaany 1425 A.H,Working Day,NaN,19:20:00,Attock,33.764500,72.3667,...,NaN,NaN,7.0,44.0,70,1.0,NaN,1.District Headquarters hospital-rwp 2.PIMS Ho...,26.665,79.997
12,13,Friday-October 1-2004,2004,17 SHa`baan 1425 A.H,Working Day,NaN,1:27 PM/1:25 PM,Sialkot,32.497200,74.5361,...,shiite,25.0,31.0,50.0,75,1.0,NaN,Allama Iqbal Memorial DHQ Hospital-Sardar Begu...,27.510,81.518
13,14,Sunday-October 10-2004,2004,26 SHa`baan 1425 A.H.,Holiday,Weekend,5:55:00/6:40:00 PM,Lahore,31.545100,74.3407,...,shiite,4.0,5.0,6.0,10,1.0,NaN,Mayo Hospital,24.390,75.902
14,15,Saturday-March 19-2005,2005,9 safar 1426 A.H,Working Day,NaN,11.45PM /10.30 pm,Quetta,30.209500,67.0182,...,Shiite,25.0,50.0,8.0,100,1.0,NaN,NaN,16.500,61.700
15,16,Thursday-April 28-2005,2005,19 Raby` al-awal 1426 A.H,Working Day,NaN,NaN,Swat,35.222700,72.4258,...,NaN,NaN,2.0,NaN,NaN,1.0,NaN,NaN,19.935,67.883
16,17,Friday-May 27-2005,2005,19 Raby` al-THaany 1426 A.H,Working Day,NaN,11:00:00,Islamabad,33.718000,73.0718,...,Shiite_sunni,20.0,25.0,82.0,100,1.0,NaN,1. PIMS 2.Polyclinic 3.CDA Hospital 4.federal ...,27.160,80.888
17,18,Monday-May 30-2005,2005,22 Raby` al-THaany 1426 A.H,Working Day,NaN,evening,Karachi,24.991800,66.9911,...,shiite,5.0,6.0,19.0,30,1.0,NaN,1. Patel Hospital 2. JMPC,31.945,89.501
18,19,Thursday-February 9-2006,2006,10 MuHarram 1427 A.H,Holiday,Ashura,09:35:00,Hangu,33.535100,71.0713,...,Shiite,37.0,40.0,90.0,NaN,1.0,NaN,Hangu Hospital,15.495,59.891
19,20,Thursday-March 2-2006,2006,2 safar 1427 A.H.,Working Day,NaN,09:00:00,Karachi,24.991800,66.9911,...,Christian,4.0,5.0,30.0,54,1.0,10-15 kg,NaN,25.300,77.540
20,21,Wednesday-April 12-2006,2006,14 Raby` al-awal 1427 A.H,Holiday,Eid Milad un-Nabi,7.00 pm,Karachi,24.991800,66.9911,...,Sunni,47.0,57.0,NaN,100,1.0,5 kg,1. Liaquat National Hospital 2. Civil Hospital...,28.415,83.147
21,22,Friday-June 2-2006,2006,6 Jumaada al-awal 1427 A.H,Working Day,NaN,10.30 am,Bannu,32.986100,70.6042,...,NaN,6.0,7.0,7.0,8,1.0,NaN,1. Combined Military 2. Hospital Peshawar,26.125,79.025
22,23,Monday-June 26-2006,2006,30 Jumaada al-awal 1427 A.H,Working Day,NaN,15:30:00,North Waziristan,32.974600,70.1456,...,NaN,6.0,7.0,NaN,26,1.0,NaN,NaN,28.610,83.498
23,24,Sunday-August 6-2006,2006,12 Rajab 1427 A.H,Holiday,Weekend,8.00 am,Lasbela,25.837700,66.5224,...,NaN,NaN,1.0,NaN,0,1.0,NaN,NaN,27.500,81.500
24,25,Wednesday-November 8-2006,2006,17 SHawwal 1427 A.H,Working Day,NaN,8.30am,Malakand,34.503000,71.9046,...,NaN,40.0,42.0,20.0,39,1.0,NaN,1. CMH Mardan\n2. CMH Peshawar,19.205,66.569
25,26,Friday-November 17-2006,2006,26 SHawwal 1427 A.H.,Working Day,NaN,7.30 am/7:15AM,Peshawar,34.004300,71.5448,...,NaN,NaN,1.0,NaN,2,1.0,NaN,NaN,17.275,63.095
26,27,Sunday-December 3-2006,2006,12 Thw al-Qi`dah 1427 A.H.,Holiday,Weekend,NaN,Bannu,32.986100,70.6042,...,NaN,NaN,1.0,NaN,1,1.0,NaN,NaN,4.705,40.469
27,28,Monday-January 22-2007,2007,3 MuHarram 1428 A.H,Working Day,NaN,10:30:00,North Waziristan,32.974600,70.1456,...,NaN,4.0,5.0,23.0,25,1.0,NaN,NaN,2.325,36.185
28,29,Friday-January 26-2007,2007,7 MuHarram 1428 A.H,Working Day,NaN,14:37:00,Islamabad,33.718000,73.0718,...,NaN,1.0,2.0,5.0,7,1.0,NaN,1.poly Clinic Hospital,16.300,61.340
29,30,Saturday-January 27-2007,2007,8 MuHarram 1428 A.H,Working Day,NaN,20:40:00,Peshawar,34.004300,71.5448,...,shiite,13.0,15.0,30.0,60,1.0,NaN,1.Lady Reading hospital,15.165,59.297
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466,467,Tuesday-Apr 19-2016,2016,10 Rajab 1437 A.H.,Working Day,NaN,NaN,Mardan,34.207854,72.0495,...,NaN,1.0,1.0,10.0,18,1.0,8-10KG,NaN,23.105,73.589
467,468,Monday-May 30-2016,2016,22 Shaban 1437 A.H.,Working Day,NaN,NaN,Mardan,34.195682,72.0378,...,NaN,1.0,1.0,12.0,15,1.0,8-10KG,Mardan district hospital.,30.020,86.036
468,469,Monday-Aug 08-2016,2016,05 Zeqad 1437 A.H.,Working Day,NaN,NaN,Quetta,30.194225,67.0088,...,NaN,70.0,70.0,112.0,120,NaN,8KG,NaN,29.585,85.253
469,470,Friday-Sep 02-2016,2016,29 Zeqad 1437 A.H.,Working Day,NaN,05:50:00,Mardan,34.195776,72.0366,...,NaN,13.0,14.0,52.0,60,1.0,6KG,NaN,27.805,82.049
470,471,Tuesday-Sep 13-2016,2016,10 Zilhaj 1437 A.H.,Holiday,Eid ul Azha Holiday,07:30:00,Shikarpur,28.002718,68.7304,...,Shiite,0.0,0.0,10.0,13,NaN,NaN,NaN,31.945,89.501
471,472,Friday-Sep 16-2016,2016,13 Zilhaj 1437 A.H.,Working Day,NaN,13:30:00,Mohmand agency,34.400331,71.5604,...,NaN,16.0,36.0,22.0,NaN,1.0,NaN,District Headquarters Hospital (DHQ) Bajaur Ag...,28.680,83.624
472,473,Tuesday-Oct-25-2016,2016,23 MuHarram 1438 A.H.,Working Day,NaN,12:00am,Quetta,30.142830,66.9819,...,NaN,58.0,61.0,100.0,165,2.0,8-10 KG,NaN,14.545,58.181
473,474,Saturday-Nov-12-2016,2016,11 safar 1438 A.H.,Weekend,NaN,18:00:00,Khuzdar,25.776775,67.0224,...,NaN,45.0,52.0,100.0,100,1.0,NaN,"Hub, Khuzdar, Lasbella and Civil Hospital in K...",NaN,NaN
474,475,Saturday-Nov-26-2016,2016,25 safar 1438 A.H.,Weekend,NaN,06:00:00,Mohmand agency,34.325826,71.3988,...,NaN,2.0,2.0,14.0,14,4.0,NaN,NaN,17.630,63.734
475,476,Tuesday-Feb-7-2017,2017,09 Jamadi-ul-Awal 1438 A.H.,Working Day,NaN,05:00:00,Bannu,32.949814,70.6091,...,NaN,0.0,0.0,2.0,2,1.0,20 KG,DHQ Hospital Bannu,19.000,NaN
476,477,Monday-Feb-13-2017,2017,16 Jumada al-awwal 1438 A.H,Working Day,NaN,18:00:00,Lahore,31.555382,74.3319,...,NaN,14.0,18.0,83.0,90,1.0,NaN,1. Mayo Hospital 2. Sir Ganga Ram Hospital,16.255,61.259
477,478,Wednesday-Feb-15-2017,2017,19 Jumada al-awwal 1438 A.H,Working Day,NaN,08:00:00,"Ghallanai, Mohmand agency",34.500000,71.3333,...,NaN,5.0,8.0,0.0,3,1.0,NaN,Lady Reading Hospital,11.115,52.007
478,479,Wednesday-Feb-15-2017,2017,19 Jumada al-awwal 1438 A.H,Working Day,NaN,15:30:00,Hayatabad,33.986111,71.456944,...,NaN,1.0,1.0,4.0,18,1.0,15 KG,Hayatabad Medical Complex,16.630,61.934
479,480,Wednesday-Feb-15-2017,2017,19 Jumada al-awwal 1438 A.H,Working Day,NaN,09:00:00,"Mosal Kor, Mohmand agency",34.553808,71.4341,...,NaN,1.0,1.0,0.0,0,1.0,NaN,NaN,NaN,NaN
480,481,Thursday-Feb-16-2017,2017,20 Jumada al-awwal 1438 A.H,Working Day,NaN,18:00:00,Sehwan town,26.419314,67.8594,...,shiite,70.0,72.0,150.0,200,1.0,NaN,1. Sehwan Taluka Hospital 2. Combined Military...,23.710,74.678
481,482,Tuesday-Feb-21-2017,2017,25 Jumada al-awwal 1438 A.H,Working Day,NaN,09:00:00,"Tangi, CharsaddaDistrict",34.300000,71.6539,...,NaN,6.0,7.0,15.0,20,2.0,NaN,Lady Reading Hospital,11.180,52.124
482,483,Wednesday-April-05-2017,2017,08 Rajab 1438 A.H,Working Day,NaN,07:15:00,Lahore,31.463017,74.4357,...,NaN,6.0,7.0,19.0,22,NaN,NaN,"Combined Military Hospital (CMH), General Hosp...",29.000,84.200
483,484,Friday-May-12-2017,2017,15 Shaban 1438 A.H,Working Day,NaN,14:30:00,Quetta,29.800833,66.8481,...,NaN,25.0,28.0,35.0,37,1.0,NaN,NaN,44.000,111.000
484,485,Saturday-May-20-2017,2017,23 Shaban 1438 A.H,Weekend,NaN,NaN,Kohat,33.387520,71.3404,...,NaN,1.0,4.0,0.0,0,NaN,NaN,NaN,37.000,99.000
485,486,Friday-June-23-2017,2017,27 RamaDHaan 1438 A.H,Working Day,NaN,13:30:00,Quetta,33.884230,70.1088,...,Shiite,30.0,85.0,100.0,100+,3.0,75KG,NaN,36.000,97.000
486,487,Monday-July-10-2017,2017,16 SHawwal 1438 A.H,Working Day,NaN,11:43:00,Chaman,30.909830,66.4524,...,NaN,1.0,3.0,1.0,11,1.0,NaN,NaN,38.000,100.000
487,488,Monday-July-17-2017,2017,22 Shawaal 1438 A.H,Working Day,NaN,NaN,Peshawar,34.015000,71.5805,...,NaN,1.0,2.0,1.0,7,1.0,NaN,NaN,37.000,98.000
488,489,Monday-July-17-2017,2017,22 Shawaal 1438 A.H,Working Day,NaN,NaN,Peshawar,34.015000,71.5805,...,NaN,1.0,1.0,1.0,1,1.0,NaN,NaN,37.000,98.000
489,490,Monday-July-24-2017,2017,29 Shawaal 1438 A.H,Working Day,NaN,15:55:00,Lahore,31.500875,74.3331,...,NaN,26.0,27.0,56.0,56,1.0,NaN,"Jinnah Hospital, General Hospital, Ittefaq Hos...",32.000,88.000
490,491,Saturday-August-12-2017,2017,12 Zeqad 1438 A.H.,Weekend,NaN,17:00:00,Quetta,30.203658,67.0045,...,NaN,15.0,15.0,40.0,40,1.0,25KG,NaN,29.000,NaN
491,492,Thursday-October-05-2017,2017,13 MuHarram 1439 A.H,Working Day,NaN,NaN,Quetta,28.571051,67.4969,...,NaN,21.0,22.0,25.0,NaN,1.0,NaN,"Larkana Hospital, Gandawah District Headquarte...",27.800,81.000
492,493,Thursday-October-19-2017,2017,27 MuHarram 1439 A.H,Working Day,NaN,08:00:00,Quetta,NaN,NaN,...,NaN,7.0,7.0,22.0,22,1.0,NaN,NaN,26.000,79.000
493,494,Thursday-November-9-2017,2017,19 Safar 1439 A.H,Working Day,NaN,07:00:00,Quetta,30.221057,67.0025,...,NaN,2.0,2.0,8.0,8,1.0,15KG,"Combined Military Hospital (CMH)-(Quetta), Civ...",25.000,77.000
494,495,Friday-November-24-2017,2017,5 Rabi Al-Awwal 1439 A.H,Working Day,NaN,07:00:00,Peshawar,33.970623,71.4386,...,NaN,1.0,3.0,6.0,8,1.0,20KG,Hayatabad Medical Complex(Peshawar),22.000,72.000
495,496,Saturday-November-25-2017,2017,6 Rabi Al-Awwal 1439 A.H,Working Day,NaN,07:00:00,Quetta,30.139626,66.9815,...,NaN,4.0,4.0,16.0,22,1.0,10KG,Civil Hospital(Quetta),29.000,84.000

In [283]:
file.Date

0        Sunday-November 19-1995
1         Monday-November 6-2000
2           Wednesday-May 8-2002
3            Friday-June 14-2002
4             Friday-July 4-2003
5      Thursday-December 25-2003
6      Saturday-February 28-2004
7              Friday-May 7-2004
8             Monday-May 31-2004
9           Thursday-June 3-2004
10        Wednesday-July 28-2004
11           Friday-July 30-2004
12         Friday-October 1-2004
13        Sunday-October 10-2004
14        Saturday-March 19-2005
15        Thursday-April 28-2005
16            Friday-May 27-2005
17            Monday-May 30-2005
18      Thursday-February 9-2006
19         Thursday-March 2-2006
20       Wednesday-April 12-2006
21            Friday-June 2-2006
22           Monday-June 26-2006
23          Sunday-August 6-2006
24     Wednesday-November 8-2006
25       Friday-November 17-2006
26        Sunday-December 3-2006
27        Monday-January 22-2007
28        Friday-January 26-2007
29      Saturday-January 27-2007
                 ...
466          Tuesday-Apr 19-2016
467           Monday-May 30-2016
468           Monday-Aug 08-2016
469           Friday-Sep 02-2016
470          Tuesday-Sep 13-2016
471           Friday-Sep 16-2016
472          Tuesday-Oct-25-2016
473         Saturday-Nov-12-2016
474         Saturday-Nov-26-2016
475           Tuesday-Feb-7-2017
476           Monday-Feb-13-2017
477        Wednesday-Feb-15-2017
478        Wednesday-Feb-15-2017
479        Wednesday-Feb-15-2017
480         Thursday-Feb-16-2017
481          Tuesday-Feb-21-2017
482      Wednesday-April-05-2017
483           Friday-May-12-2017
484         Saturday-May-20-2017
485          Friday-June-23-2017
486          Monday-July-10-2017
487          Monday-July-17-2017
488          Monday-July-17-2017
489          Monday-July-24-2017
490      Saturday-August-12-2017
491     Thursday-October-05-2017
492     Thursday-October-19-2017
493     Thursday-November-9-2017
494      Friday-November-24-2017
495    Saturday-November-25-2017
Name: Date, Length: 496, dtype: object

In [284]:
file.Date = file["Date"].str.replace("-"," ")

In [285]:
file.Date

0        Sunday November 19 1995
1         Monday November 6 2000
2           Wednesday May 8 2002
3            Friday June 14 2002
4             Friday July 4 2003
5      Thursday December 25 2003
6      Saturday February 28 2004
7              Friday May 7 2004
8             Monday May 31 2004
9           Thursday June 3 2004
10        Wednesday July 28 2004
11           Friday July 30 2004
12         Friday October 1 2004
13        Sunday October 10 2004
14        Saturday March 19 2005
15        Thursday April 28 2005
16            Friday May 27 2005
17            Monday May 30 2005
18      Thursday February 9 2006
19         Thursday March 2 2006
20       Wednesday April 12 2006
21            Friday June 2 2006
22           Monday June 26 2006
23          Sunday August 6 2006
24     Wednesday November 8 2006
25       Friday November 17 2006
26        Sunday December 3 2006
27        Monday January 22 2007
28        Friday January 26 2007
29      Saturday January 27 2007
                 ...
466          Tuesday Apr 19 2016
467           Monday May 30 2016
468           Monday Aug 08 2016
469           Friday Sep 02 2016
470          Tuesday Sep 13 2016
471           Friday Sep 16 2016
472          Tuesday Oct 25 2016
473         Saturday Nov 12 2016
474         Saturday Nov 26 2016
475           Tuesday Feb 7 2017
476           Monday Feb 13 2017
477        Wednesday Feb 15 2017
478        Wednesday Feb 15 2017
479        Wednesday Feb 15 2017
480         Thursday Feb 16 2017
481          Tuesday Feb 21 2017
482      Wednesday April 05 2017
483           Friday May 12 2017
484         Saturday May 20 2017
485          Friday June 23 2017
486          Monday July 10 2017
487          Monday July 17 2017
488          Monday July 17 2017
489          Monday July 24 2017
490      Saturday August 12 2017
491     Thursday October 05 2017
492     Thursday October 19 2017
493     Thursday November 9 2017
494      Friday November 24 2017
495    Saturday November 25 2017
Name: Date, Length: 496, dtype: object

In [286]:
file.isnull().sum()

S#                           0
Date                         0
Year                         0
Islamic Date               154
Blast Day Type              10
Holiday Type               424
Time                       211
City                         0
Latitude                     3
Longitude                    3
Province                     0
Location                     3
Location Category           36
Location Sensitivity        36
Open/Closed Space           35
Influencing Event/Event    305
Target Type                 26
Targeted Sect if any       399
Killed Min                 146
Killed                      16
Injured Min                131
Injured                     32
No. of Suicide Blasts       82
Explosive Weight (max)     324
Hospital Names             199
Temperature(C)               5
Temperature(F)               7
dtype: int64

In [287]:
file.drop("S#",axis=1,inplace=True)

In [288]:
day = []
date = []
month = []

for d in file["Date"]:
    day.append(d.split(" ")[0])
    date.append(d.split(" ")[2])
    month.append(d.split(" ")[1])
    
    
file["Date"] = date
file.insert(1,"Day",day,True)

In [289]:
file.insert(2,"Month",month,True)

In [290]:
file["Date"]

0      19
1       6
2       8
3      14
4       4
5      25
6      28
7       7
8      31
9       3
10     28
11     30
12      1
13     10
14     19
15     28
16     27
17     30
18      9
19      2
20     12
21      2
22     26
23      6
24      8
25     17
26      3
27     22
28     26
29     27
       ..
466    19
467    30
468    08
469    02
470    13
471    16
472    25
473    12
474    26
475     7
476    13
477    15
478    15
479    15
480    16
481    21
482    05
483    12
484    20
485    23
486    10
487    17
488    17
489    24
490    12
491    05
492    19
493     9
494    24
495    25
Name: Date, Length: 496, dtype: object

In [291]:
file.Month.unique()

array(['November', 'May', 'June', 'July', 'December', 'February',
       'October', 'March', 'April', 'August', 'January', 'September',
       'Aug', 'Sep', 'Oct', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr', 'Nov'],
      dtype=object)

In [292]:
file.Month.replace("Aug","August",inplace=True)
file.Month.replace("Sep","September",inplace=True)
file.Month.replace("Oct","October",inplace=True)
file.Month.replace("Nov","November",inplace=True)
file.Month.replace("Dec","December",inplace=True)
file.Month.replace("Jan","January",inplace=True)
file.Month.replace("Feb","February",inplace=True)
file.Month.replace("Mar","March",inplace=True)
file.Month.replace("Apr","April",inplace=True)

In [293]:
from datetime import datetime as dt

In [294]:
file.columns

Index(['Date', 'Day', 'Month', 'Year', 'Islamic Date', 'Blast Day Type',
       'Holiday Type', 'Time', 'City', 'Latitude', 'Longitude', 'Province',
       'Location', 'Location Category', 'Location Sensitivity',
       'Open/Closed Space', 'Influencing Event/Event', 'Target Type',
       'Targeted Sect if any', 'Killed Min', 'Killed ', 'Injured Min',
       'Injured ', 'No. of Suicide Blasts', 'Explosive Weight (max)',
       'Hospital Names', 'Temperature(C)', 'Temperature(F)'],
      dtype='object')

In [295]:
file.head()

,Date,Day,Month,Year,Islamic Date,Blast Day Type,Holiday Type,Time,City,Latitude,...,Targeted Sect if any,Killed Min,Killed,Injured Min,Injured,No. of Suicide Blasts,Explosive Weight (max),Hospital Names,Temperature(C),Temperature(F)
0,19,Sunday,November,1995,25 Jumaada al-THaany 1416 A.H,Holiday,Weekend,NaN,Islamabad,33.7180,...,NaN,14.0,15.0,NaN,60,2.0,NaN,NaN,15.835,60.503
1,6,Monday,November,2000,10 SHa`baan 1421 A.H,Working Day,NaN,NaN,Karachi,24.9918,...,NaN,NaN,3.0,NaN,3,1.0,NaN,NaN,23.770,74.786
2,8,Wednesday,May,2002,25 safar 1423 A.H,Working Day,NaN,07:45:00,Karachi,24.9918,...,Christian,13.0,15.0,20.0,40,1.0,2.5 Kg,1.Jinnah Postgraduate Medical Center 2. Civil ...,31.460,88.628
3,14,Friday,June,2002,3 Raby` al-THaany 1423 A.H,Working Day,NaN,11:10:00,Karachi,24.9918,...,Christian,NaN,12.0,NaN,51,1.0,NaN,NaN,31.430,88.574
4,4,Friday,July,2003,4 Jumaada al-awal 1424 A.H,Working Day,NaN,NaN,Quetta,30.2095,...,Shiite,44.0,47.0,NaN,65,1.0,NaN,1.CMH Quetta\n2.Civil Hospital 3. Boland Medic...,33.120,91.616

In [296]:
cols = ["Date","Year"]
file[cols] = file[cols].astype("int")

In [297]:
from hijri_converter import convert

In [298]:
hijri_date = []

for i in file[["Year","Month","Date"]].values:
    year = i[0]
    month = i[1]
    day = i[2]
    datetime_object = dt.strptime(month, "%B")
    month_number = datetime_object.month
    x = convert.Gregorian(year,int(month_number),day).to_hijri()
    h_date = x.dmyformat().split("/")[0]
    h_month = x.month_name()
    h_year = x.dmyformat().split("/")[2]
    hijri_date.append(str(h_date)+ " " + h_month + " " + str(h_year))

In [299]:
hijri_date

['26 Jumada al-Akhirah 1416',
 '10 Shaâ€™ban 1421',
 '25 Safar 1423',
 '03 Rabiâ€™ al-Thani 1423',
 '04 Jumada al-Ula 1424',
 '02 Dhul-Qiâ€™dah 1424',
 '08 Muharram 1425',
 '18 Rabiâ€™ al-Awwal 1425',
 '12 Rabiâ€™ al-Thani 1425',
 '15 Rabiâ€™ al-Thani 1425',
 '11 Jumada al-Akhirah 1425',
 '13 Jumada al-Akhirah 1425',
 '17 Shaâ€™ban 1425',
 '26 Shaâ€™ban 1425',
 '09 Safar 1426',
 '19 Rabiâ€™ al-Awwal 1426',
 '19 Rabiâ€™ al-Thani 1426',
 '22 Rabiâ€™ al-Thani 1426',
 '10 Muharram 1427',
 '02 Safar 1427',
 '14 Rabiâ€™ al-Awwal 1427',
 '06 Jumada al-Ula 1427',
 '30 Jumada al-Ula 1427',
 '12 Rajab 1427',
 '17 Shawwal 1427',
 '26 Shawwal 1427',
 '12 Dhul-Qiâ€™dah 1427',
 '03 Muharram 1428',
 '07 Muharram 1428',
 '08 Muharram 1428',
 '10 Muharram 1428',
 '15 Muharram 1428',
 '15 Muharram 1428',
 '18 Muharram 1428',
 '29 Muharram 1428',
 '10 Rabiâ€™ al-Awwal 1428',
 '11 Rabiâ€™ al-Thani 1428',
 '28 Rabiâ€™ al-Thani 1428',
 '11 Jumada al-Ula 1428',
 '19 Jumada al-Akhirah 1428',
 '27 Jumada al-Akhirah 1428',
 '27 Jumada al-Akhirah 1428',
 '29 Jumada al-Akhirah 1428',
 '01 Rajab 1428',
 '01 Rajab 1428',
 '03 Rajab 1428',
 '03 Rajab 1428',
 '05 Rajab 1428',
 '05 Rajab 1428',
 '05 Rajab 1428',
 '06 Rajab 1428',
 '13 Rajab 1428',
 '20 Rajab 1428',
 '21 Rajab 1428',
 '04 Shaâ€™ban 1428',
 '06 Shaâ€™ban 1428',
 '06 Shaâ€™ban 1428',
 '07 Shaâ€™ban 1428',
 '11 Shaâ€™ban 1428',
 '13 Shaâ€™ban 1428',
 '19 Shaâ€™ban 1428',
 '19 Shaâ€™ban 1428',
 '22 Shaâ€™ban 1428',
 '22 Shaâ€™ban 1428',
 '29 Shaâ€™ban 1428',
 '01 Ramadhan 1428',
 '10 Ramadhan 1428',
 '19 Ramadhan 1428',
 '06 Shawwal 1428',
 '13 Shawwal 1428',
 '18 Shawwal 1428',
 '20 Shawwal 1428',
 '28 Shawwal 1428',
 '14 Dhul-Qiâ€™dah 1428',
 '14 Dhul-Qiâ€™dah 1428',
 '24 Dhul-Qiâ€™dah 1428',
 '29 Dhul-Qiâ€™dah 1428',
 '30 Dhul-Qiâ€™dah 1428',
 '03 Dhul-Hijjah 1428',
 '05 Dhul-Hijjah 1428',
 '07 Dhul-Hijjah 1428',
 '11 Dhul-Hijjah 1428',
 '13 Dhul-Hijjah 1428',
 '17 Dhul-Hijjah 1428',
 '28 Dhul-Hijjah 1428',
 '01 Muharram 1429',
 '06 Muharram 1429',
 '08 Muharram 1429',
 '23 Muharram 1429',
 '26 Muharram 1429',
 '27 Muharram 1429',
 '02 Safar 1429',
 '04 Safar 1429',
 '09 Safar 1429',
 '09 Safar 1429',
 '18 Safar 1429',
 '22 Safar 1429',
 '23 Safar 1429',
 '24 Safar 1429',
 '26 Safar 1429',
 '03 Rabiâ€™ al-Awwal 1429',
 '03 Rabiâ€™ al-Awwal 1429',
 '09 Rabiâ€™ al-Awwal 1429',
 '12 Rabiâ€™ al-Awwal 1429',
 '25 Rabiâ€™ al-Thani 1429',
 '01 Jumada al-Ula 1429',
 '04 Jumada al-Ula 1429',
 '13 Jumada al-Ula 1429',
 '28 Jumada al-Ula 1429',
 '03 Rajab 1429',
 '10 Rajab 1429',
 '12 Shaâ€™ban 1429',
 '18 Shaâ€™ban 1429',
 '20 Shaâ€™ban 1429',
 '22 Shaâ€™ban 1429',
 '28 Shaâ€™ban 1429',
 '06 Ramadhan 1429',
 '16 Ramadhan 1429',
 '20 Ramadhan 1429',
 '20 Ramadhan 1429',
 '22 Ramadhan 1429',
 '24 Ramadhan 1429',
 '03 Shawwal 1429',
 '06 Shawwal 1429',
 '09 Shawwal 1429',
 '09 Shawwal 1429',
 '10 Shawwal 1429',
 '16 Shawwal 1429',
 '26 Shawwal 1429',
 '29 Shawwal 1429',
 '02 Dhul-Qiâ€™dah 1429',
 '04 Dhul-Qiâ€™dah 1429',
 '06 Dhul-Qiâ€™dah 1429',
 '08 Dhul-Qiâ€™dah 1429',
 '08 Dhul-Qiâ€™dah 1429',
 '13 Dhul-Qiâ€™dah 1429',
 '14 Dhul-Qiâ€™dah 1429',
 '19 Dhul-Qiâ€™dah 1429',
 '22 Dhul-Qiâ€™dah 1429',
 '30 Dhul-Qiâ€™dah 1429',
 '03 Dhul-Hijjah 1429',
 '05 Dhul-Hijjah 1429',
 '07 Dhul-Hijjah 1429',
 '11 Dhul-Hijjah 1429',
 '30 Dhul-Hijjah 1429',
 '07 Muharram 1430',
 '07 Muharram 1430',
 '26 Muharram 1430',
 '10 Safar 1430',
 '10 Safar 1430',
 '11 Safar 1430',
 '14 Safar 1430',
 '25 Safar 1430',
 '26 Safar 1430',
 '28 Safar 1430',
 '05 Rabiâ€™ al-Awwal 1430',
 '14 Rabiâ€™ al-Awwal 1430',
 '19 Rabiâ€™ al-Awwal 1430',
 '26 Rabiâ€™ al-Awwal 1430',
 '29 Rabiâ€™ al-Awwal 1430',
 '30 Rabiâ€™ al-Awwal 1430',
 '03 Rabiâ€™ al-Thani 1430',
 '08 Rabiâ€™ al-Thani 1430',
 '08 Rabiâ€™ al-Thani 1430',
 '09 Rabiâ€™ al-Thani 1430',
 '19 Rabiâ€™ al-Thani 1430',
 '22 Rabiâ€™ al-Thani 1430',
 '10 Jumada al-Ula 1430',
 '16 Jumada al-Ula 1430',
 '26 Jumada al-Ula 1430',
 '03 Jumada al-Akhirah 1430',
 '04 Jumada al-Akhirah 1430',
 '04 Jumada al-Akhirah 1430',
 '12 Jumada al-Akhirah 1430',
 '13 Jumada al-Akhirah 1430',
 '16 Jumada al-Akhirah 1430',
 '18 Jumada al-Akhirah 1430',
 '19 Jumada al-Akhirah 1430',
 '19 Jumada al-Akhirah 1430',
 '29 Jumada al-Akhirah 1430',
 '03 Rajab 1430',
 '07 Rajab 1430',
 '08 Rajab 1430',
 '09 Rajab 1430',
 '15 Rajab 1430',
 '06 Shaâ€™ban 1430',
 '22 Shaâ€™ban 1430',
 '24 Shaâ€™ban 1430',
 '25 Shaâ€™ban 1430',
 '27 Shaâ€™ban 1430',
 '30 Shaâ€™ban 1430',
 '01 Ramadhan 1430',
 '02 Ramadhan 1430',
 '06 Ramadhan 1430',
 '09 Ramadhan 1430',
 '22 Ramadhan 1430',
 '23 Ramadhan 1430',
 '28 Ramadhan 1430',
 '29 Ramadhan 1430',
 '02 Shawwal 1430',
 '07 Shawwal 1430',
 '07 Shawwal 1430',
 '09 Shawwal 1430',
 '16 Shawwal 1430',
 '20 Shawwal 1430',
 '23 Shawwal 1430',
 '26 Shawwal 1430',
 '26 Shawwal 1430',
 '27 Shawwal 1430',
 '01 Dhul-Qiâ€™dah 1430',
 '04 Dhul-Qiâ€™dah 1430',
 '05 Dhul-Qiâ€™dah 1430',
 '14 Dhul-Qiâ€™dah 1430',
 '14 Dhul-Qiâ€™dah 1430',
 '20 Dhul-Qiâ€™dah 1430',
 '21 Dhul-Qiâ€™dah 1430',
 '22 Dhul-Qiâ€™dah 1430',
 '25 Dhul-Qiâ€™dah 1430',
 '25 Dhul-Qiâ€™dah 1430',
 '26 Dhul-Qiâ€™dah 1430',
 '28 Dhul-Qiâ€™dah 1430',
 '02 Dhul-Hijjah 1430',
 '14 Dhul-Hijjah 1430',
 '15 Dhul-Hijjah 1430',
 '17 Dhul-Hijjah 1430',
 '20 Dhul-Hijjah 1430',
 '20 Dhul-Hijjah 1430',
 '21 Dhul-Hijjah 1430',
 '28 Dhul-Hijjah 1430',
 '30 Dhul-Hijjah 1430',
 '01 Muharram 1431',
 '05 Muharram 1431',
 '07 Muharram 1431',
 '07 Muharram 1431',
 '11 Muharram 1431',
 '15 Muharram 1431',
 '20 Muharram 1431',
 '22 Muharram 1431',
 '22 Muharram 1431',
 '01 Safar 1431',
 '08 Safar 1431',
 '14 Safar 1431',
 '26 Safar 1431',
 '27 Safar 1431',
 '04 Rabiâ€™ al-Awwal 1431',
 '06 Rabiâ€™ al-Awwal 1431',
 '08 Rabiâ€™ al-Awwal 1431',
 '13 Rabiâ€™ al-Awwal 1431',
 '19 Rabiâ€™ al-Awwal 1431',
 '22 Rabiâ€™ al-Awwal 1431',
 '26 Rabiâ€™ al-Awwal 1431',
 '27 Rabiâ€™ al-Awwal 1431',
 '13 Rabiâ€™ al-Thani 1431',
 '13 Rabiâ€™ al-Thani 1431',
 '20 Rabiâ€™ al-Thani 1431',
 '20 Rabiâ€™ al-Thani 1431',
 '02 Jumada al-Ula 1431',
 '03 Jumada al-Ula 1431',
 '04 Jumada al-Ula 1431',
 '05 Jumada al-Ula 1431',
 '14 Jumada al-Ula 1431',
 '17 Jumada al-Ula 1431',
 '18 Jumada al-Ula 1431',
 '14 Jumada al-Akhirah 1431',
 '19 Rajab 1431',
 '27 Rajab 1431',
 '30 Rajab 1431',
 '06 Shaâ€™ban 1431',
 '14 Shaâ€™ban 1431',
 '23 Shaâ€™ban 1431',
 '13 Ramadhan 1431',
 '22 Ramadhan 1431',
 '24 Ramadhan 1431',
 '24 Ramadhan 1431',
 '27 Ramadhan 1431',
 '30 Ramadhan 1431',
 '28 Shawwal 1431',
 '10 Dhul-Qiâ€™dah 1431',
 '24 Dhul-Qiâ€™dah 1431',
 '28 Dhul-Qiâ€™dah 1431',
 '05 Dhul-Hijjah 1431',
 '05 Dhul-Hijjah 1431',
 '08 Dhul-Hijjah 1431',
 '24 Dhul-Hijjah 1431',
 '30 Dhul-Hijjah 1431',
 '01 Muharram 1432',
 '02 Muharram 1432',
 '04 Muharram 1432',
 '17 Muharram 1432',
 '18 Muharram 1432',
 '19 Muharram 1432',
 '21 Muharram 1432',
 '08 Safar 1432',
 '21 Safar 1432',
 '23 Safar 1432',
 '27 Safar 1432',
 '07 Rabiâ€™ al-Awwal 1432',
 '08 Rabiâ€™ al-Awwal 1432',
 '09 Rabiâ€™ al-Awwal 1432',
 '16 Rabiâ€™ al-Awwal 1432',
 '26 Rabiâ€™ al-Awwal 1432',
 '28 Rabiâ€™ al-Awwal 1432',
 '04 Rabiâ€™ al-Thani 1432',
 '19 Rabiâ€™ al-Thani 1432',
 '25 Rabiâ€™ al-Thani 1432',
 '26 Rabiâ€™ al-Thani 1432',
 '27 Rabiâ€™ al-Thani 1432',
 '29 Rabiâ€™ al-Thani 1432',
 '30 Rabiâ€™ al-Thani 1432',
 '03 Jumada al-Ula 1432',
 '19 Jumada al-Ula 1432',
 '10 Jumada al-Akhirah 1432',
 '11 Jumada al-Akhirah 1432',
 '22 Jumada al-Akhirah 1432',
 '23 Jumada al-Akhirah 1432',
 '25 Jumada al-Akhirah 1432',
 '03 Rajab 1432',
 '10 Rajab 1432',
 '11 Rajab 1432',
 '23 Rajab 1432',
 '10 Shaâ€™ban 1432',
 '20 Shaâ€™ban 1432',
 '23 Shaâ€™ban 1432',
 '06 Ramadhan 1432',
 '11 Ramadhan 1432',
 '19 Ramadhan 1432',
 '02 Shawwal 1432',
 '03 Shawwal 1432',
 '09 Shawwal 1432',
 '17 Shawwal 1432',
 '21 Shawwal 1432',
 '01 Dhul-Hijjah 1432',
 '11 Dhul-Hijjah 1432',
 '20 Dhul-Hijjah 1432',
 '22 Dhul-Hijjah 1432',
 '29 Muharram 1433',
 '09 Safar 1433',
 '09 Safar 1433',
 '09 Safar 1433',
 '20 Safar 1433',
 '07 Rabiâ€™ al-Awwal 1433',
 '25 Rabiâ€™ al-Awwal 1433',
 '24 Rabiâ€™ al-Awwal 1433',
 '02 Rabiâ€™ al-Thani 1433',
 '10 Rabiâ€™ al-Thani 1433',
 '11 Rabiâ€™ al-Thani 1433',
 '18 Rabiâ€™ al-Thani 1433',
 '22 Rabiâ€™ al-Thani 1433',
 '30 Rabiâ€™ al-Thani 1433',
 '13 Jumada al-Ula 1433',
 '13 Jumada al-Akhirah 1433',
 '22 Rajab 1433',
 '08 Shaâ€™ban 1433',
 '26 Shaâ€™ban 1433',
 '16 Shawwal 1433',
 '23 Shawwal 1433',
 '27 Dhul-Qiâ€™dah 1433',
 '19 Dhul-Hijjah 1433',
 '22 Dhul-Hijjah 1433',
 '23 Dhul-Hijjah 1433',
 '05 Muharram 1434',
 '07 Muharram 1434',
 '07 Muharram 1434',
 '11 Muharram 1434',
 '15 Muharram 1434',
 '20 Muharram 1434',
 '21 Muharram 1434',
 '09 Safar 1434',
 '28 Safar 1434',
 '20 Rabiâ€™ al-Awwal 1434',
 '04 Rabiâ€™ al-Thani 1434',
 '04 Rabiâ€™ al-Thani 1434',
 '06 Rabiâ€™ al-Thani 1434',
 '08 Rabiâ€™ al-Thani 1434',
 '06 Jumada al-Ula 1434',
 '11 Jumada al-Ula 1434',
 '17 Jumada al-Ula 1434',
 '06 Jumada al-Akhirah 1434',
 '06 Jumada al-Akhirah 1434',
 '10 Jumada al-Akhirah 1434',
 '13 Jumada al-Akhirah 1434',
 '19 Jumada al-Akhirah 1434',
 '21 Jumada al-Akhirah 1434',
 '27 Jumada al-Akhirah 1434',
 '28 Jumada al-Akhirah 1434',
 '01 Rajab 1434',
 '02 Rajab 1434',
 '14 Rajab 1434',
 '24 Rajab 1434',
 '06 Shaâ€™ban 1434',
 '06 Shaâ€™ban 1434',
 '09 Shaâ€™ban 1434',
 '12 Shaâ€™ban 1434',
 '21 Shaâ€™ban 1434',
 '29 Shaâ€™ban 1434',
 '17 Ramadhan 1434',
 '18 Ramadhan 1434',
 '01 Shawwal 1434',
 '16 Dhul-Qiâ€™dah 1434',
 '26 Dhul-Qiâ€™dah 1434',
 '27 Dhul-Qiâ€™dah 1434',
 '06 Dhul-Hijjah 1434',
 '11 Dhul-Hijjah 1434',
 '13 Muharram 1435',
 '16 Muharram 1435',
 '19 Muharram 1435',
 '14 Safar 1435',
 '15 Safar 1435',
 '17 Safar 1435',
 '29 Safar 1435',
 '05 Rabiâ€™ al-Awwal 1435',
 '08 Rabiâ€™ al-Awwal 1435',
 '19 Rabiâ€™ al-Awwal 1435',
 '22 Rabiâ€™ al-Awwal 1435',
 '28 Rabiâ€™ al-Awwal 1435',
 '04 Rabiâ€™ al-Thani 1435',
 '07 Rabiâ€™ al-Thani 1435',
 '10 Rabiâ€™ al-Thani 1435',
 '13 Rabiâ€™ al-Thani 1435',
 '24 Rabiâ€™ al-Thani 1435',
 '02 Jumada al-Ula 1435',
 '13 Jumada al-Ula 1435',
 '24 Jumada al-Akhirah 1435',
 '12 Rajab 1435',
 '06 Shaâ€™ban 1435',
 '10 Shaâ€™ban 1435',
 '11 Shaâ€™ban 1435',
 '21 Shaâ€™ban 1435',
 '26 Shaâ€™ban 1435',
 '29 Dhul-Qiâ€™dah 1435',
 '10 Dhul-Hijjah 1435',
 '21 Dhul-Hijjah 1435',
 '29 Dhul-Hijjah 1435',
 '09 Muharram 1436',
 '24 Safar 1436',
 '06 Rabiâ€™ al-Awwal 1436',
 '10 Rabiâ€™ al-Thani 1436',
 '24 Rabiâ€™ al-Thani 1436',
 '28 Rabiâ€™ al-Thani 1436',
 '29 Rabiâ€™ al-Thani 1436',
 '24 Jumada al-Ula 1436',
 '29 Jumada al-Ula 1436',
 '17 Rajab 1436',
 '08 Shaâ€™ban 1436',
 '08 Shaâ€™ban 1436',
 '11 Shaâ€™ban 1436',
 '19 Shaâ€™ban 1436',
 '21 Shaâ€™ban 1436',
 '24 Shaâ€™ban 1436',
 '12 Ramadhan 1436',
 '01 Shawwal 1436',
 '01 Dhul-Qiâ€™dah 1436',
 '12 Dhul-Qiâ€™dah 1436',
 '17 Dhul-Qiâ€™dah 1436',
 '07 Dhul-Hijjah 1436',
 '01 Muharram 1437',
 '09 Muharram 1437',
 '10 Muharram 1437',
 '18 Rabiâ€™ al-Awwal 1437',
 '03 Rabiâ€™ al-Thani 1437',
 '09 Rabiâ€™ al-Thani 1437',
 '19 Rabiâ€™ al-Thani 1437',
 '27 Rabiâ€™ al-Thani 1437',
 '27 Jumada al-Ula 1437',
 '18 Jumada al-Akhirah 1437',
 '09 Rajab 1437',
 '12 Rajab 1437',
 '23 Shaâ€™ban 1437',
 '05 Dhul-Qiâ€™dah 1437',
 '01 Dhul-Hijjah 1437',
 '12 Dhul-Hijjah 1437',
 '15 Dhul-Hijjah 1437',
 '24 Muharram 1438',
 '12 Safar 1438',
 '26 Safar 1438',
 '10 Jumada al-Ula 1438',
 '16 Jumada al-Ula 1438',
 '18 Jumada al-Ula 1438',
 '18 Jumada al-Ula 1438',
 '18 Jumada al-Ula 1438',
 '19 Jumada al-Ula 1438',
 '24 Jumada al-Ula 1438',
 '08 Rajab 1438',
 '16 Shaâ€™ban 1438',
 '24 Shaâ€™ban 1438',
 '28 Ramadhan 1438',
 '16 Shawwal 1438',
 '23 Shawwal 1438',
 '23 Shawwal 1438',
 '01 Dhul-Qiâ€™dah 1438',
 '20 Dhul-Qiâ€™dah 1438',
 '15 Muharram 1439',
 '29 Muharram 1439',
 '20 Safar 1439',
 '06 Rabiâ€™ al-Awwal 1439',
 '07 Rabiâ€™ al-Awwal 1439']

In [300]:
file["Islamic Date"] = hijri_date

In [301]:
file["Holiday Type"].unique()

array(['Weekend', nan, 'Christmas/birthday of Quaid-e-Azam', 'Ashura',
       'Eid Milad un-Nabi', 'Iqbal Day', 'Eid-ul-azha', 'Labour Day',
       'Eid-ul-Fitar', 'Pakistan Day', 'Defence Day',
       'Christmas/ birthday of Quaid-e-Azam', 'General Elections',
       'Eid Holidays', 'Ashura Holiday', 'Eid ul Azha Holiday'],
      dtype=object)

In [302]:
file["Holiday Type"].replace("Ashura Holiday","Ashura",inplace=True)

In [303]:
null_index = file[file["Blast Day Type"].isnull()].index.values

In [304]:
null_index

array([413, 431, 434, 435, 436, 437, 438, 439, 440, 441], dtype=int64)

In [305]:
file[file["Blast Day Type"].isnull()]

,Date,Day,Month,Year,Islamic Date,Blast Day Type,Holiday Type,Time,City,Latitude,...,Targeted Sect if any,Killed Min,Killed,Injured Min,Injured,No. of Suicide Blasts,Explosive Weight (max),Hospital Names,Temperature(C),Temperature(F)
413,23,Thursday,January,2014,22 Rabiâ€™ al-Awwal 1435,NaN,NaN,NaN,Peshawar,34.0043,...,NaN,NaN,6.0,NaN,8,NaN,NaN,NaN,11.110,51.998
431,15,Wednesday,October,2014,21 Dhul-Hijjah 1435,NaN,NaN,NaN,Tirah Valley,33.8679,...,NaN,NaN,7.0,NaN,5,NaN,NaN,NaN,17.210,62.978
434,16,Tuesday,December,2014,24 Safar 1436,NaN,NaN,NaN,Peshawar,34.0043,...,NaN,NaN,148.0,NaN,132,NaN,NaN,NaN,9.860,49.748
435,28,Sunday,December,2014,06 Rabiâ€™ al-Awwal 1436,NaN,NaN,NaN,Zhob,31.3500,...,NaN,NaN,2.0,NaN,0,NaN,NaN,NaN,8.445,47.201
436,30,Friday,January,2015,10 Rabiâ€™ al-Thani 1436,NaN,NaN,NaN,Shikarpur,28.0000,...,NaN,60.0,62.0,NaN,39,NaN,NaN,NaN,16.225,61.205
437,13,Friday,February,2015,24 Rabiâ€™ al-Thani 1436,NaN,NaN,NaN,Peshawar,34.0043,...,NaN,NaN,21.0,NaN,60,NaN,NaN,NaN,17.235,63.023
438,17,Tuesday,February,2015,28 Rabiâ€™ al-Thani 1436,NaN,NaN,NaN,Lahore,31.5451,...,NaN,5.0,9.0,NaN,NaN,NaN,NaN,NaN,18.680,65.624
439,18,Wednesday,February,2015,29 Rabiâ€™ al-Thani 1436,NaN,NaN,NaN,Rawalpindi,33.6000,...,NaN,NaN,5.0,NaN,6,NaN,NaN,NaN,15.250,59.450
440,15,Sunday,March,2015,24 Jumada al-Ula 1436,NaN,NaN,NaN,Lahore,31.5451,...,NaN,NaN,17.0,70.0,72,NaN,NaN,NaN,18.630,65.534
441,20,Friday,March,2015,29 Jumada al-Ula 1436,NaN,NaN,NaN,Karachi,24.9918,...,NaN,2.0,3.0,0.0,0,NaN,NaN,NaN,27.000,80.600

In [306]:
file["Blast Day Type"][413] = "Working Day"
file["Blast Day Type"][431] = "Working Day"
file["Blast Day Type"][434] = "Working Day"
file["Blast Day Type"][435] = "Weekend"
file["Blast Day Type"][436] = "Working Day"
file["Blast Day Type"][437] = "Working Day"
file["Blast Day Type"][438] = "Working Day"
file["Blast Day Type"][439] = "Working Day"
file["Blast Day Type"][440] = "Weekend"
file["Blast Day Type"][441] = "Working Day"

C:\Users\MY PC\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\MY PC\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\MY PC\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\MY PC\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\MY PC\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\MY PC\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\MY PC\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
C:\Users\MY PC\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\MY PC\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
C:\Users\MY PC\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

In [307]:
file["Blast Day Type"].unique()

array(['Holiday', 'Working Day', 'Weekend'], dtype=object)

In [308]:
file['Weekend'] = file['Day'].apply(lambda x: 1 if ((x == "Saturday") | (x == "Sunday")) else 0)

In [309]:
file.isnull().sum()

Date                         0
Day                          0
Month                        0
Year                         0
Islamic Date                 0
Blast Day Type               0
Holiday Type               424
Time                       211
City                         0
Latitude                     3
Longitude                    3
Province                     0
Location                     3
Location Category           36
Location Sensitivity        36
Open/Closed Space           35
Influencing Event/Event    305
Target Type                 26
Targeted Sect if any       399
Killed Min                 146
Killed                      16
Injured Min                131
Injured                     32
No. of Suicide Blasts       82
Explosive Weight (max)     324
Hospital Names             199
Temperature(C)               5
Temperature(F)               7
Weekend                      0
dtype: int64

In [246]:
file.columns

Index(['Date', 'Day', 'Month', 'Year', 'Islamic Date', 'Blast Day Type',
       'Holiday Type', 'Time', 'City', 'Latitude', 'Longitude', 'Province',
       'Location', 'Location Category', 'Location Sensitivity',
       'Open/Closed Space', 'Influencing Event/Event', 'Target Type',
       'Targeted Sect if any', 'Killed Min', 'Killed ', 'Injured Min',
       'Injured ', 'No. of Suicide Blasts', 'Explosive Weight (max)',
       'Hospital Names', 'Temperature(C)', 'Temperature(F)', 'Weekend'],
      dtype='object')

In [310]:
file.dropna(subset=["Location","Longitude","Latitude"],inplace=True)

In [311]:
file["Hospital Names"].unique()

array([nan,
       '1.Jinnah Postgraduate Medical Center 2. Civil Hospital Karachi3. PN Shifa',
       '1.CMH Quetta\n2.Civil Hospital 3. Boland Medical Complex',
       '1.District headquarters \nHospital ', 'Civil hospital ',
       'Civil hospital-Liaquat National hospital-Jinnah Postgraduate Medical Center',
       'CMH Kohat',
       '1.District Headquarters hospital-rwp 2.PIMS Hospital 3. Tehsil headquarters hospital-Fateh Jang',
       'Allama Iqbal Memorial DHQ Hospital-Sardar Begum Hospital-and numner of other hospitals in Sialkot-Daska-Gujranwala and Lahore',
       'Mayo Hospital ',
       '1. PIMS 2.Polyclinic 3.CDA Hospital 4.federal govt services 5.rwp generl hosp',
       '1. Patel Hospital 2. JMPC', 'Hangu Hospital ',
       '1. Liaquat National Hospital 2. Civil Hospital KHI 3. JPMC 4. Abbasi Shaheed Hospital',
       '1. Combined Military 2. Hospital Peshawar',
       '1. CMH Mardan\n2. CMH Peshawar', '1.poly Clinic Hospital ',
       '1.Lady Reading hospital ', '1.DIK Headquarters \nHospital ',
       '1.CMH  Dera',
       '1.Quttea Civil hospital \n2.Bolan medical hospital ',
       '1.Combined Military\n Hospital ',
       '1.District Headquarters Hospital\n 2.Lady Reading Hospital ',
       '1.Lady Reading Hospital ', '1.CMH Peshawar',
       '1.Agency Headquarters \nhospital ', '1.CMH Bannu hospital',
       '1.District Headquarters \nHospital ',
       '1.Fedral govt services hospital 2.PIMS',
       '1.Federal Government\n services hospital\n2.Capital Development \nAuthority hospital ',
       '1.Agency Headqurters \nHospital ', '1.Nawagai hospital ',
       '1.Bannu Hospital ',
       '1.District Headquarters Rwp\n2.Rwp General Hospital',
       'DI Khan Headquarter\n hospital ',
       '1.Wapda Hospital    2.CMH Pindi \n3.CMH Attock',
       '1.District Headquartar \nHospital ',
       '1.Jinnah Hospital \n2.Liaquat hospital ',
       '1.Saidu Shrif hospital ', '1.CMH 2.Civil hospital',
       '1.PAF Sargodha \n2.CMH Rwp', '1.Hayatabad Medical Complex',
       '1.Military Hospital \n2.Rawalpindi hospital ', '1.CMH Rwp',
       '1.CMH hospital ', '1.CMH Nowshera', 'Combine Military hospital',
       'Rawalpindi General hospital', '1.Mayo-Ganga ram hospital ',
       'Ghalani hospital ', '1.CMH bannu 2.MH Bannu', '1.CMH 2.MH 3. DHQ',
       '1.Lady Reading Hospital 2. DHQ Charsadda',
       'District headquarters hospital saidu sharif',
       'Agency headquarter hospital',
       '1.CMH 2.MH 3.Contonment hospital 4. rwp general hospital 5. DHQ hospital',
       '1.Lady Reading Hospital 2.Hayatabad medical Complex',
       '1.CMH 2.Service hospital', '1.Ganga Ram Hospita 2.Mayo Hospital ',
       'Ganga Ram hospital ', 'Saidu Sharif hospital',
       'Military Hospital ', '1.DHQ 2.CMH',
       '1.district headquarters hospital saidu sharif ',
       '1.CMH 2.District Headqurtar Hospital ',
       '1.PIMS 2.Federal Government Service Hospital',
       '1.PIMS 2.Poly Clinic 3.Federal Government Service Hospital',
       '1.Sheikh Zahid Hospital', '1.Combined Military Hospital ',
       'pof hospital', '1.Saidu sharif hospital ', '1.CMH Kohat',
       'Lady Reading Hospital-Khyber teaching-Hayatabad complex',
       '1.Poly Clinic  2. PIMS', '1.CMH Hospital 2.Civil Hospital',
       '1.District Hospital Charsadda', '1.Nishtar Hospital Multan',
       '1. PIMS 2.Federal Government Services',
       '1.KohatDvisional Headquarters Hospital  2.Gahluj hospital 3.Hospitals in Hangu and Kohat',
       '1.Ghalaanai Hospital ', 'district headquarter hospital',
       'CMH Hangu', 'Syedo Shrif Hospital ',
       '1.Lady Reading Hospital 2.Combined Military Hospital ',
       'District hospital Bajur', 'Kalidya Hospital ',
       'Poly clinic multan ',
       'Local Hospital In DG Khan/Nishtar Hospital',
       'Jamrud Civil Hospital', 'DHQ Hospital Bannu  / PeshawarHospital',
       '1. DHQ D.I.Khan\n2. Nishtar Hospital\n3. Lady Reading Pesh',
       'Civil hospital Quetta', 'Lady Reading Hospital ',
       'DHQ Hospital RWP\n2. Benazir Hospital RWP', 'Civil Hospital Tank',
       'Peshwar Hospitals', 'PIMS\nPolyclinic ',
       'CharsaddaDHQ/Tangi Hospital/JamalAbad hospital/PeshawarHospital',
       'Civil Hospital Hangu/ CMH Thall',
       'Khyber Teaching Hospital / Hayatabad Medical Complex',
       '1. Lady Reading Hospital Pesh\n2. CMH Peshwar',
       'CMH Dera/ TankHospitals',
       'Ganga Ram hospital / Meo/ Services Hospital',
       'Lady Reading Hospital \nPeshawar', 'PIMS', 'LRH ',
       'Mayo-Sir Ganga Ram Servuces-Jinnah Hospital',
       'contonment hospital-DHQ Hospital-PeshawarCMH', 'CMH Muzzafarabad',
       'Lady Reading Hospital', 'Landi Kotal Hospital',
       'Alpuri Hospital ', 'KohatHospital ', 'Govt Hospital Kamra',
       'CMH-Distric headquarter hospital-militry hospital-combined military hospital',
       'mian munchi hospital-mayo hospital',
       'Lady Reading Hospital-combined military hospital-khyber teaching hospital-\nPeshawar',
       '1. LRH Peshawar\n2. Khyber Teaching\n3. Hayatabad Medical ',
       '1. CMH Rawalpindi\n2. DHQ Rawalpindi\n3. AFIC      4.MH',
       '1. Jinnah Hospital\n2. Sheikh Zahyad Hospital\n3. Mayo Hospital 4.services hospital-5.farooq hospital',
       '1. CMH\n2. Nishtar Hospital ', 'district headquarters hospitals',
       'DHQ Timergara', 'Near local hospital ', 'CMH Rawala kot',
       'District headquarter hospital Timra',
       '1.Hayatabad Meical hospital',
       '1.District Headquarter Hospital Bannu  2.Combined Military Hospital',
       'Mashte hospital', '1.Manseehra District Headquarters Hospital ',
       '1.CMH Hospital 2.Seydo Hospital',
       'District Headquarter Hospital Karak',
       '1.CMH Tal Hospital 2.District Headquarters hospital hangu',
       '1.Jinna Hospital 2.General Hosptal 3.shaikh zayed Hospital 4.Ittefaq Hospital',
       'Children Hospital', '1. Judical Complex ',
       'Agency headquarter hospital in Khar',
       '1.Lady Reading Hospital 2.Khaber Teaching Hospital',
       '1.Civil Hospital 2.Bolan Medical Complex 3. CMH',
       '1.District Headquarter Hospital  2.Liaqat Hospital',
       'District Headquarter Hospital',
       '1. Mayo Hospital\n2. Sir Ganga Ram Hospital \n3. Services Hospital ',
       'Lady Reading Hospital Peshwar',
       '1)Mayo Hospital 2)Sir ganga Ram Hospital  ',
       '1.Combined Miltry Hospital                2.Civil Hospital ',
       '1.Civil Hospital      2.DHQ Hospital',
       '1. JPMC\n2. Civil Hospital KHI', '1.Judicial Complex ',
       '1.District Headqurters Hospital 2.Lady reading hospital ',
       '1.Zahid hospital ', 'Wana hospital',
       '1.Tehsil Headquarters Ghalani \n2.Lady Reading ', 'CMH ',
       'Hospitals in KohatDivision', 'lady Reading Hospital-CMH',
       "Bannu's Main hospital", 'Mayo Hospital-ganagaram hospital',
       'CMH Mardan-CMH rawalpindi', 'CMH Thall',
       'Shahmansoor Hospital Complex/Swabi District Hospital/khunda Civil Hospital and  LRH Peshawar',
       'Lady reading hospital',
       'sakhi sarwar civil hospital-dera district headquarters hospital',
       'Temargara Hospital', 'Civil hospital-CMH',
       'Agency headquarter hospital in Miranshah',
       'Lady reading hospital-khyber teaching complex-hayatabad medical complex',
       'hungu district headquarter hospital',
       'khar agency headquarter hospital',
       'PIMS-Shifa International hospital',
       'Battagram District Headquarters hospital', 'Jandola hospital',
       'Tehsil Headquarters hospital Jamrud-Hayatabad Medical complex-Khyber Teaching Hospital',
       'city hospitals ', 'Jinnah Postgraduate Medical Center',
       'CMH Bannu', 'Khyber teaching Hospital',
       'District Headquarters Hospital', 'Agency Headquarter Hospital',
       'Lady Reading Hospital (LRH)',
       'Hayatabad Medical Hospital-Khyber Teaching Hospital',
       'Agency Headquarters Hospital (AHH)-Lady Reading Hospital (LRH)-',
       'Civil hospital-Bolan Medical Complex-CMH',
       'District Hospital Bannu',
       'Khyber Teaching Hospital-American Club',
       'District Headquarters Hospital ',
       'Abbasi Shaheed Hospital-Sindh Police & Rangers Hospital-PNS Shifa Hospital',
       'Ghallanai Headquarter Hospital',
       'Qatar Hospital-Abbasi Shaheed Hospital',
       'DHQ-Combined Military-Benazir Bhutto Hospital',
       'District Headquarter Teaching Hospital-Combined Military Hospital',
       'Tehsil Headquarter Hospital Wana', 'DHQ Hospital Bannu',
       'First Treatment Hospital',
       'Civil Hospital and the Combined Military Hospital-Quetta',
       'DHQ-Kohat', 'Civil Hospital and the Combined Military Hospital',
       'Military Hospital Miranshah',
       'Headquarter Hospital Bajour Agency', 'Khyber Teaching Hospital',
       'Government Hospital Bannu', 'Civil Hospital',
       'Bolan Medical Complex Quetta',
       ' Tehsil Headquarters Takht Bhai-Mardan Medical Complex and Lady Reading Hospital in Peshawar',
       'Bolan Medical Complex Quetta-CMH-Civil Hospital',
       'Parachinar Headquarters Hospital',
       'Civil Hospital and CMH Quetta',
       'Hayatabad Medical Complex-Peshawar',
       'Benazir Bhutto Hospital and District Headquarters Hospital',
       'Jinnah Hospital', 'Bolan Medical Complex',
       'Agha Khan University Hospital', 'Abbasi Shaheed Hospital',
       'Pakistan Institute of Medical Sciences', 'DHQ Fateh Jang',
       'CMH Quetta',
       'Bolan Medical Complex Hospital-Combined Military Hospital (CMH)',
       'General Hospital Lahore-', 'Ali Zai Hospital',
       'Hayatabad Medical Complex', 'Bhag Hospital',
       'Jacobabad Civil Hospital',
       'district headquarters hospitaldistrict headquarters hospital',
       'Civil Hospital, CMH ', 'Hayatabad Medical Complex ',
       'Civil Hospital Zhob', 'Civil Hospital Quetta- CMH ',
       'Jinnah Hospital,Sheikh Zaid Hospital,Services Hospital,Farooq Hospital,Meo Hospital,Bajwa Hospital',
       'Mardan district hospital.',
       'District Headquarters Hospital (DHQ) Bajaur Agency',
       'Hub, Khuzdar, Lasbella and Civil Hospital in Karachi',
       ' 1. Mayo Hospital 2.  Sir Ganga Ram Hospital',
       '1. Sehwan Taluka Hospital 2. Combined Military Hospital Hyderabad',
       'Combined Military Hospital (CMH), General Hospital',
       'Jinnah Hospital, General Hospital, Ittefaq Hospital',
       'Larkana Hospital, Gandawah District Headquarters Hospital, 1 shifted to Aga Khan Hospital KHI',
       'Combined Military Hospital (CMH)-(Quetta), Civil Hospital(Quetta)',
       'Hayatabad Medical Complex(Peshawar)', 'Civil Hospital(Quetta)'],
      dtype=object)

In [312]:
file["Hospital Names"] = file["Hospital Names"].str.strip(" ")
file["Hospital Names"].replace(" ","",inplace=True)
file["Hospital Names"].replace("1. ","",inplace=True)
file["Hospital Names"].replace("1.","",inplace=True)
file["Hospital Names"].replace(" 1","",inplace=True)
file["Hospital Names"].replace("1)","",inplace=True)
file["Hospital Names"].replace("2. ","/",inplace=True)
file["Hospital Names"].replace("2.","/",inplace=True)
file["Hospital Names"].replace("3. ","/",inplace=True)
file["Hospital Names"].replace("3.","/",inplace=True)
file["Hospital Names"].replace("4. ","/",inplace=True)
file["Hospital Names"].replace("\n"," ",inplace=True)
file["Hospital Names"].replace("\n2.","/",inplace=True)
file["Hospital Names"].replace("\n3.","/",inplace=True)
file["Hospital Names"].replace(",","/",inplace=True)
file["Hospital Names"].replace("-","/",inplace=True)

In [313]:
file["Time"].fillna("NA",inplace=True)

In [320]:
file.to_csv("suicide_bombings.csv")